Add the secp256k1 curve
arkworks-rs/curves pull request #122
Opened 2022-09-05 01:29 UTC by weikengchen

## Description

Relies on https://github.com/arkworks-rs/algebra/pull/469. When that one is merged, we will need to update the Cargo.toml to point to the `master` branch of algebra.

A change is needed to fix the constraint tests.

Closes: #36 
It also makes the branch `secp256k1` obsolete. @npwardberkeley 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

N/A:
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code

2022-09-05 01:29 UTC, weikengchen commented on Cargo.toml
> +ark-ff = { git = "https://github.com/arkworks-rs/algebra"}
```suggestion
ark-ff = { git = "https://github.com/arkworks-rs/algebra" }
```

2022-09-05 01:29 UTC, weikengchen commented on curve-constraint-tests/src/lib.rs
>              let modulus_last_limb_bits = <C::ScalarField as PrimeField>::MODULUS_BIT_SIZE % 64;
```suggestion

            let modulus_last_limb_bits = <C::ScalarField as PrimeField>::MODULUS_BIT_SIZE % 64;
```

2022-09-06 17:24 UTC, Pratyush commented
Instead of implementing it on BigInt320, how about we port the techniques from [the crrl library](https://github.com/pornin/crrl/blob/3a3e625d784b4234d53829771fc3e18abab16913/src/backend/w64/modint.rs#L14)? That avoids allocating an extra limb.

Also, we can port the specialized arithmetic from the base field over.

2022-10-29 18:31 UTC, weikengchen commented
@Pratyush Let me create an issue to cover this topic, and probably for this PR we will just let it be this.

2022-12-09 07:47 UTC, weikengchen commented
This PR is ready.

2022-12-09 08:09 UTC, Pratyush requested changes

2022-12-09 08:09 UTC, Pratyush commented on secp256k1/src/lib.rs
> +//! Vesta:
```suggestion
```

2022-12-09 08:09 UTC, Pratyush commented on secq256k1/src/lib.rs
> +//! Vesta:
```suggestion
```

2022-12-09 08:09 UTC, Pratyush commented on secq256k1/src/lib.rs
> +//! This library implements the secq256k1 curve.
Could you add a reference for the definition of the curve?

2022-12-09 08:09 UTC, Pratyush commented on secp256k1/src/lib.rs
> +//!
Could you add a reference for the curve definition?

2022-12-09 09:00 UTC, weikengchen commented
Sources added.

2022-12-09 09:00 UTC, weikengchen commented on secq256k1/src/lib.rs
> +//! This library implements the secq256k1 curve.
DONE

2022-12-09 09:00 UTC, weikengchen commented on secp256k1/src/lib.rs
> +//!
DONE

2022-12-09 17:40 UTC, Pratyush commented on secp256k1/src/lib.rs
> +//!
Can you do this also for secq?

2022-12-09 17:42 UTC, Pratyush commented on secp256k1/src/lib.rs
> +//!
And by source, I meant a formal description of the curve constants, e.g. https://en.bitcoin.it/wiki/Secp256k1

2022-12-09 17:44 UTC, Pratyush commented on secp256k1/src/lib.rs
> +//!
Or something like this: https://www.secg.org/sec2-v2.pdf

2022-12-09 18:04 UTC, weikengchen commented
Fixed. I incorrectly put the secq one in the secp. Now it is fixed. For secq I think that thread is the citation that we generally use when referring to secq.

2022-12-09 18:04 UTC, weikengchen commented on secp256k1/src/lib.rs
> +//! Source: <https://en.bitcoin.it/wiki/Secp256k1>
Fixed as here.

2022-12-09 18:04 UTC, weikengchen commented on secq256k1/src/lib.rs
> +//! Source: <https://moderncrypto.org/mail-archive/curves/2018/000992.html>
Fixed as here.

2022-12-09 18:41 UTC, Pratyush approved these changes

2022-12-09 18:41 UTC, merged

2022-12-09 18:45 UTC, weikengchen commented
I deleted the `secp256k1` branch as well. (@npwardberkeley Nick Ward's  previous attempt)